save_dir: save/
model_name: BertQA
# model_weights: bert-base-uncased
# model_weights: bert-large-uncased-whole-word-masking-finetuned-squad
# model_weights: save/bert_weights/x/bert-large-squad-docvqa-finetuned
model_weights: rubentito/bert-large-mpdocvqa
device: cuda
data_parallel: True

training_parameters:
  lr: 5e-5
  batch_size: 20
  train_epochs: 10
  warmup_iterations: 1000
