save_dir: save/
model_name: BigBird
# model_weights: abhinavkulkarni/bigbird-roberta-base-finetuned-squad
# model_weights: google/bigbird-base-trivia-itc  # TriviaQA
model_weights: weights/bigbird-base-trivia-itc
device: cuda

training_parameters:
  lr: 3e-5
  batch_size: 8
  train_epochs: 10
  warmup_iterations: 1000
