save_dir: save/
model_name: Donut
model_weights: naver-clova-ix/donut-base-finetuned-docvqa
# model_weights: weights/t5_oracle_mp-docvqa__best.ckpt
# model_weights: rubentito/t5-base-mpdocvqa
device: cuda
data_parallel: False

training_parameters:
  lr: 2e-4  # 2e-4
  batch_size: 2
  train_epochs: 10
  warmup_iterations: 1000
