save_dir: save/
model_name: Hi-VLT5
# model_weights: t5-base
# model_weights: weights/t5_oracle_mp-docvqa__best.ckpt
# model_weights: weights/lt5_oracle_mp-docvqa__best.ckpt
model_weights: weights/hilt5_custom_mp-docvqa__best.ckpt
freeze_encoder: False
page_tokens: 10
device: cuda
data_parallel: False

retrieval_module:
  loss: CrossEntropy
  loss_weight: 0.25

visual_module:
#  model: 'vit'
#  model_weights: 'google/vit-base-patch16-224-in21k'
  model: 'dit'
  model_weights: 'microsoft/dit-base-finetuned-rvlcdip'

training_parameters:
  lr: 2e-4  # 2e-4
  batch_size: 2
  train_epochs: 10
  warmup_iterations: 1000
  seed: 42
