save_dir: save/
model_name: LayoutLMv2
# model_weights: microsoft/layoutlmv2-base-uncased
model_weights: tiennvcs/layoutlmv2-base-uncased-finetuned-docvqa
# model_weights: xhyi/layoutlmv3-large_docvqa_t13c11000
device: cuda

training_parameters:
  lr: 5e-05  # 5e-05 From the ModelCard in Huggingface (https://huggingface.co/tiennvcs/layoutlmv2-base-uncased-finetuned-docvqa) -- 2e-4
  batch_size: 2
  train_epochs: 10
  warmup_iterations: 1000
