save_dir: save/
model_name: LayoutLMv2
# model_weights: microsoft/layoutlmv2-base-uncased  # 1e-4
# model_weights: tiennvcs/layoutlmv2-base-uncased-finetuned-docvqa  # 5e-5
model_weights: weights/layoutlmv2_oracle_mp-docvqa.ckpt
device: cuda

training_parameters:
  lr: 1e-4  # 5e-5 From the ModelCard in Huggingface (https://huggingface.co/tiennvcs/layoutlmv2-base-uncased-finetuned-docvqa) -- 2e-4
  batch_size: 2
  train_epochs: 10
  warmup_iterations: 1000
