save_dir: save/
model_name: Longformer
model_weights: valhalla/longformer-base-4096-finetuned-squadv1
# Model_weights: mrm8488/longformer-base-4096-finetuned-squadv2
# Model_weights: allenai/longformer-base-4096-finetuned-triviaqa
device: cuda

training_parameters:
  lr: 1e-4  # (Longformer Colab) # 3e-5  # (Original Longformer paper) # 2e-4  # (LayoutHT5)
  batch_size: 4
  train_epochs: 10
  warmup_iterations: 1000

