save_dir: save/
model_name: LT5
# model_weights: t5-base
model_weights: weights/t5_oracle_mp-docvqa__best.ckpt
device: cuda

training_parameters:
  lr: 2e-4  # 2e-4
  batch_size: 3
  train_epochs: 10
  warmup_iterations: 1000
