save_dir: save/
model_name: VT5
# model_weights: t5-base
# model_weights: weights/t5_oracle_mp-docvqa__best.ckpt
model_weights: rubentito/t5-base-mpdocvqa
max_source_length: 512
device: cuda
data_parallel: False

training_parameters:
  lr: 2e-4  # 2e-4
  batch_size: 2
  train_epochs: 10
  warmup_iterations: 1000

visual_module:
  model: 'dit'  # 'vit' / 'dit'
  model_weights: 'microsoft/dit-base-finetuned-rvlcdip'  # 'google/vit-base-patch16-224-in21k' / 'microsoft/dit-base-finetuned-rvlcdip'

