includes:
  - configs/datasets/SQuAD_dag.yml

save_dir: save/
Model: BertQA
# Model_weights: bert-large-uncased-whole-word-masking-finetuned-squad
Model_weights: save/bert_weights/x/bert-large-squad-docvqa-finetuned
device: cuda

training_parameters:
  lr: 2e-4
  batch_size: 2
  train_epochs: 10
  warmup_iterations: 1000
