imdb_dir: /SSD/Datasets/DocVQA/Task1/pythia_data/imdb/docvqa/
save_dir: save/
Model: BertQA
# Model_weights: bert-large-uncased-whole-word-masking-finetuned-squad
Model_weights: save/bert_weights/bert-large-squad-docvqa-finetuned
train_epochs: 10
batch_size: 2
device: cuda
