includes:
  - configs/datasets/SQuAD.yml

save_dir: save/
Model: Longformer
Model_weights: valhalla/longformer-base-4096-finetuned-squadv1
# Model_weights: mrm8488/longformer-base-4096-finetuned-squadv2
# Model_weights: allenai/longformer-base-4096-finetuned-triviaqa
device: cuda

training_parameters:
  lr: 3e-5  # 2e-4
  batch_size: 3
  train_epochs: 10
  warmup_iterations: 1000
