dataset_name: MP-DocVQA
imdb_dir: /data/users/rperez/imdb/collection  # /imdb/collection/imdb_train.npy
images_dir: /data/users/rperez/DocVQA_UCSF/images
page_retrieval: Oracle  # Oracle / Concat / Logits
