dataset_name: MP-DocVQA
imdb_dir: /data/users/rperez/imdb/collection  # /imdb/collection/imdb_train.npy
images_dir: /data/users/rperez/MP-DocVQA/images/
page_retrieval: Oracle  # Oracle / Concat / Logits / Custom (for Hi-LT5)
max_pages: 20
