dataset_name: MP-DocVQA
imdb_dir: /content/datasets # /imdb/collection/imdb_train.npy
images_dir: /content/datasets/images
page_retrieval: Oracle  # Oracle / Concat / Logits / Custom (for Hierarchical methods (Hi-LayoutLMv3, Hi-LT5, Hi-VT5)
